name: Build and run ASan

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

env:
  BUILD_TYPE: ASan

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DHAVE_SANITIZER=1

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} 

    - name: ASan
      working-directory: ${{github.workspace}}/build
      run: |
        ./foldcomp compress ../test.pdb
        ./foldcomp decompress ../test.fcz
      
