name: Lint python

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: psf/black@stable
      with:
        options: "--check"
        src: "."
  build:
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        python: ["3.7", "3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python}}
      - run: |
          pip install poetry
          poetry build --no-interaction
          poetry install --no-interaction